services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: shopsphere_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: shopsphere_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres_test:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: shopsphere_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: shopsphere_test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
  redis_data: